### PR TITLE
Basic README

### PR DESCRIPTION
**Pull request by zsusswein**
Simple placeholder readme with overview and a few citations, as discussed.

### CODE REVIEW

**Review by seabbs — APPROVED** [review]

**Comment by seabbs** [comment]
I think as it stands only Katie can okay PRs here? Though that branch protection message makes me think its even stronger and no PRs are allowed at all (which would need to be changed obviously)

**Comment by zsusswein** [comment]
Oh I messed something up. I'll go fiddle with the settings some more.

**Comment by kgostic** [comment]
This looks great to me. Does @seabbs want to be listed as an admin?

**Review by kgostic — APPROVED** [review]

**Comment by zsusswein** [comment]
He's already in the CODEOWNERS file and is an admin. Problem was in the branch protection rules, but should be fixed now.

**Pull request merged**
